FROM quay.io/frrouting/frr:10.4.1

# shadow is required to run useradd
RUN apk add --no-cache openssh shadow

# Generate host keys (required for sshd to run)
RUN ssh-keygen -A

# Add an user that always logs int to vtysh (frrvty group is required for permissions)
RUN useradd -m -s /usr/bin/vtysh -G frrvty netadmin
RUN echo "netadmin:super-strong-password" | chpasswd
