frr version 10.4.1_git
frr defaults traditional
hostname PE2
log syslog informational
service integrated-vtysh-config

! =============================================================================
!                                  Interfaces
! =============================================================================
interface eth1
    ip address 10.0.4.0/31
exit
interface eth2
    ip address 10.0.2.0/31
exit
interface eth3
    ip address 172.16.0.2/24
exit
interface lo0
    ip address 192.168.3.2/32
exit

! =============================================================================
!                                      BGP
! =============================================================================
router bgp 65020
    no bgp ebgp-requires-policy
    no bgp network import-check

    bgp router-id 192.168.3.2
    
    neighbor 10.0.2.1 remote-as 65001
    neighbor 10.0.4.1 remote-as 65002
    neighbor IBGP-PEERS peer-group
    neighbor IBGP-PEERS remote-as 65020
    neighbor IBGP-PEERS next-hop-self
    
    neighbor 172.16.0.1 peer-group IBGP-PEERS
    neighbor 172.16.0.3 peer-group IBGP-PEERS
    neighbor 172.16.0.4 peer-group IBGP-PEERS
exit