frr version 10.4.1_git
frr defaults traditional
hostname UP1
log syslog informational
service integrated-vtysh-config

! =============================================================================
!                                  Interfaces
! =============================================================================
interface eth1
    ip address 10.0.5.1/31
exit
interface lo131
    ip address 131.114.0.1/16
exit
interface lo192
    ip address 192.0.2.1/24
exit
interface lo198
    ip address 198.51.100.1/24
exit
interface lo203
    ip address 203.0.113.1/24
exit
interface lo0
    ip address 192.168.4.1/32
exit

! =============================================================================
!                                      BGP
! =============================================================================
router bgp 65004
    no bgp ebgp-requires-policy
    no bgp network import-check

    bgp router-id 192.168.4.1
    
    neighbor 10.0.5.0 remote-as 65020
    network 131.114.0.0/16
    network 192.0.2.0/24
    network 198.51.100.0/24
    network 203.0.113.0/24
exit